<a href="https://colab.research.google.com/github/shilpagandham2/Capstone_MITxPRO_TelcoChurn_ShilaNaiduGandham/blob/main/The_covariance_is_positive%2C_indicating_Ads_and_Sales_move_in_the_same_direction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("tiny_ads_sales.csv")
df

Day  Ads  Sales
0    1   10     20
1    2   20     40
2    3   30     50
3    4   40     80
4    5   50     90

In [5]:
ads = df["Ads"]
sales = df["Sales"]

In [6]:
print("Mean Ads:", np.mean(ads))
print("Std Ads:", np.std(ads))

print("Mean Sales:", np.mean(sales))
print("Std Sales:", np.std(sales))

Mean Ads: 30.0
Std Ads: 14.142135623730951
Mean Sales: 56.0
Std Sales: 25.768197453450252


In [7]:
plt.scatter(ads, sales)
plt.xlabel("Ads Spend")
plt.ylabel("Sales")
plt.title("Ads vs Sales")
plt.show()

In [8]:
print("Covariance Matrix:\n", np.cov(ads, sales))
print("\nCorrelation Matrix:\n", np.corrcoef(ads, sales))

Covariance Matrix:
 [[250. 450.]
 [450. 830.]]

Correlation Matrix:
 [[1.         0.98787834]
 [0.98787834 1.        ]]


In [9]:
corr = np.corrcoef(ads, sales)[0,1]

if corr > 0.8:
    print("\nStrong positive relationship")
elif corr > 0.3:
    print("\nModerate relationship")
else:
    print("\nWeak relationship")


Strong positive relationship


In [15]:
np.corrcoef(ads, sales)


array([[1.        , 0.98787834],
       [0.98787834, 1.        ]])

In [16]:
corr_value = np.corrcoef(ads, sales)[0, 1]

print("Correlation Matrix:\n", np.corrcoef(ads, sales))

print(f"\nCorrelation coefficient: {corr_value:.2f}")

print(
    "\nInterpretation: "
    "Ads spend and Sales exhibit a very strong positive linear relationship."
)

Correlation Matrix:
 [[1.         0.98787834]
 [0.98787834 1.        ]]

Correlation coefficient: 0.99

Interpretation: Ads spend and Sales exhibit a very strong positive linear relationship.
